# Generated by Django 4.1.7 on 2023-03-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image3',
        ),
    ]
